# Site settings
title: Joshua Miller Digital Portfolio
email: https://formspree.io/f/xzboaolj
url: https://joshua-miller1.github.io
description: "A Digital Porfolio, examples from Computer Science and Cybersecurity"
keywords: ""
skills: "Computer Science - Cybersecurity"
meta_author: Miller Joshua

# Google webmaster tools
google_verify:

bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7b7b7b #18bc9c #80B3FF - darker grey 
  primary-rgb: "123,123,123"  #"24,288,156" #"128,179,255" - grey 
  secondary: ff0f0f  #2c3e50 #FD6E8A - red 
  secondary-dark: 233140  #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: http://github.com/joshua-miller1

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
