# Site settings
title: Joshua Miller Digital Portfolio
email: /f/xzboaolj
url: https://joshua-miller1.github.io
description: "Career Objective: Recent graduate in Computer Science and Cybersecurity searching for an internship for the summer of 2022. I have the intention of working for my Masters of Business Administration in Cybersecurity."
keywords: ""
skills: "Programming in Java, Python, C++ - Experience with HTML and CSS - Research Cybertreats and APT groups - Network Scanning with NMAP"
meta_author: Miller Joshua

# Google webmaster tools
google_verify:

bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  #backgrounds 
  primary: 697e92 #efe2ba
  primary-rgb: "195, 212, 163" #"105,126,146" #"239,226,186"
  # nav bar and footer and text color on white 
  secondary: 4694d4
  # text highlight in nav bar 
  secondary-dark: 2f4f5f  

# Footer settings
footer:
  copyright: Joshua Miller
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jt-miller/
  - title: github
    url: http://github.com/joshua-miller1

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits:
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
